name: 'build'

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Linux dependencies (only on ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            libsoup2.4-dev \
            libgtk-3-dev \
            jq

      - name: Install app dependencies and build it
        run: |
          pnpm install
          pnpm tauri build

      - name: List build output
        run: ls -R src-tauri/target/release/bundle

      - name: Set version from tauri.conf.json
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            $VERSION = (Get-Content -Raw -Path src-tauri/tauri.conf.json | ConvertFrom-Json).package.version
            echo "VERSION=$VERSION" >> $env:GITHUB_ENV
          else
            VERSION=$(jq -r '.package.version' < src-tauri/tauri.conf.json)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi

      - name: Print Version
        run: echo "The version is ${{ env.VERSION }}"

      - name: Create GitHub Release Draft
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.MOONMARS_TOKEN }}
        with:
          tagName: ${{ env.VERSION }}
          releaseName: 'v${{ env.VERSION }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false

      - name: Upload Bundles to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: src-tauri/target/release/bundle/*/*
          token: ${{ secrets.MOONMARS_TOKEN }}
          name: 'v${{ env.VERSION }}'
          tag_name: '${{ env.VERSION }}'
          body: 'See the assets to download this version and install.'
          draft: false
          prerelease: false
